### ISSUE TITLE
Uncaught ContextHasNotBegunYet: E4C_TRY

### ISSUE THREAD

**Issue by darkoverlordofdata** [guillermocalvo/exceptions4c#7]
Yes, I read the first issue, but the faq it links to is gone from this repo.
I'm trying a helloworld exception - 
```c
#include "e4c.h"
int main(int argc, char **argv) {
    int foo;
    try{
        throw(UserQuitException, "I Quit");
        foo = 1;
    }catch(UserQuitException){
        foo = 123;
    }
    return 0;    
}```
But it fails when it get's to the 'try'. I tried compiling with and without thread support, and I get the same error.

clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\msys64\mingw64\bin

**Comment by guillermocalvo** [comment]
Sorry, I intended to update the wiki, but haven't found the time to do it yet. 😅 

In order to use `try`, `catch`, `throw`, etc. you need to call function [`e4c_context_begin`](https://github.com/guillermocalvo/exceptions4c/blob/master/src/e4c.h#L1562 "Introduces a block of code which will use a new exception context") first. Typically you want to do this just once, in your `main` function; and you need to call [`e4c_context_end`](https://github.com/guillermocalvo/exceptions4c/blob/master/src/e4c.h#L2973 "Ends the current exception context") before your program exits.

Each function is thoroughly documented inside the header file [`e4c.h`](https://github.com/guillermocalvo/exceptions4c/blob/master/src/e4c.h "exceptions4c header file"), but don't hesitate to reopen this ticket or create a new one if you need help.

**Comment by hadichahine** [comment]
@guillermocalvo Do you plan on omitting these calls? Is that even possible?
